### ISSUE TITLE
Package side-effects

### ISSUE THREAD

**Issue by moorereason** [gobuffalo/flect#18]
Importing `flect` causes the surprising ("[magical](https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html)" per Peter Bourgon) side-effects referenced below.  Could these side effects be removed?  They seem like an implementation detail that ought to be left up to the caller.

https://github.com/gobuffalo/flect/blob/d4fc286952bf96d0262a67b482e234613ae36f59/custom_data.go#L13-L16

Related to #16.

**Comment by markbates** [comment]
They’re a feature, so no, they won’t be removed. You can set the env to a path that doesn’t have the files, or just not have the files.
