### ISSUE TITLE
Port Humanize feature

### ISSUE THREAD

**Issue by moorereason** [gobuffalo/flect#19]
The `Humanize` function has not been ported [from markbates/inflect](https://github.com/markbates/inflect/blob/d582c680dc4d29c2279628ae00e743005bfcd4fe/inflect.go#L528).  Was that intentional?

Hugo uses that function internally and also exports it as [a template function](https://github.com/gohugoio/hugo/blob/30a7c9ea37a0f36451946f8688a3f807618a7eff/tpl/inflect/inflect.go#L40).  However, Hugo don't use the `AddHuman()` capabilities, so the `humans` Ruleset isn't needed for our use case.

**Comment by markbates** [comment]
Not intentional. Probably just an oversight. Feel free and open a PR.

-----------
Mark Bates

**Comment by stanislas-m** [comment]
Fixed with #22.
