### ISSUE TITLE
Pluralization and capitalization issues

### ISSUE THREAD

**Issue by dvli2007** [gobuffalo/flect#20]
`Pluralize()` should in theory pluralize a name while maintaining the cases. For example, `FooBar -> FooBars`.

However, there are a few cases where the pluralization produces unintentional lowercasing.

1. `Half -> halves`
    It seems that when the whole word matches an item in the `singularToPlural` map, the entire word gets converted in lowercase. On the contrary, this seems to behave correctly when a singular word is attached to another one, such as the case of `LemonHalf -> LemonHalves`.

2. `SmartPerson -> Smartpeople`
    It seems that when the suffix matches one of the `pluralRules`, the entire matched portion remains lowercase.

3. `SuperbOx -> Superboxes`
    It seems that camel-casing is not respected for breaking up words. ~In fact, the `pluralRules` seem to be applied first (`box -> boxes`) before the `singularToPlural` rules (`ox -> oxen`).~ In fact, it seems that when `ox` is attached to another word, it will never be changed to `oxen` (example: `big_ox -> big_oxes`).

Overall, having consistent behavior here is important as this package is used by `gobuffalo/pop` for auto-generating table names from camel-case structs. Happy to help discuss potential solutions!

**Comment by markbates** [comment]
PRs welcome. Please. :)

-----------
Mark Bates

**Comment by pgier** [comment]
PR #29 should fix the `big_ox -> big_oxes` issue

**Comment by rameshgkwd05** [comment]
The above PR #29 covers multi-words.
But what about general words, those should be pluralized according to this Grammarly article: https://www.grammarly.com/blog/plural-nouns/

Maybe a more elegant suffix-function is needed.

**Comment by sio4** [comment]
fixed by #59
