### ISSUE TITLE
Bug in name.Folder()

### ISSUE THREAD

**Issue by tobiashienzsch** [gobuffalo/flect#24]
See [`gobuffalo/buffalo` issue #1769](https://github.com/gobuffalo/buffalo/issues/1769).

The problem seems to be in  [/flect/name/folder.go:22](https://github.com/gobuffalo/flect/blob/master/name/folder.go#L22)

**Testcase**
This testcase should pass:
```go
{"NameOthername", "name_othernames"},
```
but it produces:
```go
"name/othername"
```

**Comment by sio4** [comment]
Indeed, this behavior does not help Buffalo's generator as the original issue explained. However, from the perspective of Flect, it can be a breaking change so will work on it after feezing the v1 series.
