### ISSUE TITLE
Humanize capitalization inconsistency

### ISSUE THREAD

**Issue by fazalmajid** [gobuffalo/flect#25]
Humanize() is working differently than in github.com/markbates/inflect:

```
package main

import (
	"fmt"
	"github.com/gobuffalo/flect"
	"github.com/markbates/inflect"
)

func main() {
	fmt.Println("github.com/markbates/inflect: ", inflect.Humanize("MyCamel"))
	fmt.Println("github.com/gobuffalo/flect: ", flect.Humanize("MyCamel"))
}
```

yields:

```
github.com/markbates/inflect:  My camel
github.com/gobuffalo/flect:  My Camel
```

This isn't conforming to the documented behavior, which says
> Humanize returns first letter of sentence capitalized employee_salary = Employee salary employee_id = employee ID employee_mobile_number = Employee mobile number"

**Comment by tsmith1024** [comment]
Added #27 with an update to the documentation. If a letter is capitalized in the source string, it will remain capitalized in the result string.
