### ISSUE TITLE
Flect translating Field into Fieldren

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/flect#33]
Flect seems to be translating some words wrongly. If I use v0.2.0 `user_custom_field` plural gets translated to `user_custom_fieldren` instead of `user_custom_fields`. It works with v0.1.7.

I noticed this behavior with pop queries:

```
SELECT user_custom_fieldren.created_at, user_custom_fieldren.custom_field_id, user_custom_fieldren.id, user_custom_fieldren.updated_at, user_custom_fieldren.user_id, user_custom_fieldren.value FROM user_custom_fieldren AS user_custom_fieldren WHERE user_id = $1
```

**Comment by sio4** [comment]
It seems like this issue was fixed in the current version. Added a test case for this in the working PR, and closing.
