### ISSUE TITLE
Capitalize complete acronym if it is first segment of pascalized ident

### ISSUE THREAD

**Issue by breml** [gobuffalo/flect#39]
If the first segment of an ident is an acronym, only the first letter gets capitalized in method `Pascalize`.

e.g. `ip_address` is pascalized to `IpAddress`, I expected to get `IPAddress`.

For public types in Go, go lint complains, if e.g. `ip` is not capitalized to `IP`.

**Comment by sio4** [comment]
Thanks for bring this issue and fixing it!
