### ISSUE TITLE
Replace an existing rule

### ISSUE THREAD

**Issue by renathoaz** [gobuffalo/flect#47]
AddPlural doesn't replace an existing rule but append it to the list.

let's say I want replace suffix: "o" to "os".

When call pluralize it won't achieve this new rule, 'cause it is in the end of the list, 
so pluralize will do the default one {"o", "oes"} first and return.

is there any possibility to change it ? when add new rule if it exists replace it.

**Comment by renathoaz** [comment]
a simple fix is changing the append order of function AddPlural,
so the new rule will be executed first in pluralize function.

```

// AddPlural adds a rule that will replace the given suffix with the replacement suffix.
func AddPlural(suffix string, repl string) {
	pluralMoot.Lock()
	defer pluralMoot.Unlock()
	pluralRules = append([]rule{{
		suffix: suffix,
		fn: func(s string) string {
			s = s[:len(s)-len(suffix)]
			return s + repl
		},
	}}, pluralRules...)

	pluralRules = append([]rule{{
		suffix: repl,
		fn:     noop,
	}}, pluralRules...)
}
```
has this change a chance to be applied ?

**Comment by sio4** [comment]
#48 fixed this. Closing.

Thanks for your contribution!
