### ISSUE TITLE
bug: Singular form of "invoices" is "invoice"

### ISSUE THREAD

**Issue by travisnewhouse** [gobuffalo/flect#61]
#### Description

The singular form of "invoices" is "invoice".  Similar words are "voices" -> "voice" and "choices" -> "choice".  Flect.Singularize() does not return the correct singular form of these words.  As a side note, flect.Pluralize() does return the proper plural form of the singular form of these words.

#### Expected Behavior

flect.Singularize("invoices") == "invoice"
flect.Singularize("voices") == "voice"
flect.Singularize("choices") == "choice"

#### Actual Behavior

flect.Singularize("invoices") == "invoex"
flect.Singularize("voices") == "voex"
flect.Singularize("choices") == "choex"

**Comment by sio4** [comment]
Thanks for reporting this! Indeed, this is a bug and should be fixed as soon as possible.

I took a look at the code shortly and I think we need to fix the logic. We currently use a single table for both s-to-p and p-to-s, but they are not always reversible. I will check again soon.

**Comment by sio4** [comment]
FYI, I am working on it with some other fundamental changes.
