### ISSUE TITLE
bug: Regression in Humanize with unicode accents

### ISSUE THREAD

**Issue by bep** [gobuffalo/flect#67]
### Description

I have a failing test case in Hugo when trying to update from  0.3.0 to 1.0.1:

Input: `óbito`
Expected: `Óbito`
Got `Ã\xa3 bito`

https://github.com/gohugoio/hugo/pull/10751

### Additional Context

Details

<details>

```
Paste the output of `buffalo info` here!
```

</details>

**Comment by sio4** [comment]
Thank you for filing the issue. Confirmed, and the fix is on its way.

**Comment by sio4** [comment]
Just released v1.0.2 with the patch. Please use the fixed version!
